AWSTemplateFormatVersion: 2010-09-09
# Reference: https://docs.aws.amazon.com/codebuild/latest/userguide/cloudformation-vpc-template.html
# Some explanation on resources https://www.infoq.com/articles/aws-vpc-cloudformation/
Description: Rentaboat's CloudFormation stack template
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
